Repository Good-LuckyNews/Good-LuckyNews-FE, pull requests merged in 2025-03, with the labels that each got.

#21 Fix: merge 중 생긴 오류 수정
  src/navigations/MainTab.jsx
  src/screens/index.js
Labels: bug

#25 Feat: 기사 홈, 굿피드, 기사 크롤링 API 연결
  App.js
  src/components/Feed/Feed.jsx
  src/components/Feed/FeedList.jsx
  src/components/My/Scrap.jsx
  src/contexts/EditContext.jsx
  src/contexts/ScrapContext.jsx
  src/contexts/index.js
  src/screens/GoodFeed/GoodFeed.jsx
  src/screens/GoodFeed/GoodFeedDetail.jsx
  src/screens/Home.jsx
  src/screens/Login/SignUpPreference.js
Labels: enhancement, API

#26 Feat: 마이페이지, 홈, 피드 API 연동
  package-lock.json
  package.json
  src/components/Feed/Feed.jsx
  src/components/Feed/FeedList.jsx
  src/components/Graph/Graph.jsx
  src/components/My/MyCustomTopTabs.jsx
  src/components/My/Scrap.jsx
  src/screens/GoodFeed/GoodFeed.jsx
  src/screens/Login/SignUpPreference.js
  src/screens/MyPage/MyPage.jsx
  src/screens/MyPage/ProfileEdit.jsx
Labels: enhancement, API

#27 Feat: 로딩 아이콘 및 기사 피드 html 태그 제거 코드 추가
  src/components/Feed/Feed.jsx
  src/components/Feed/FeedList.jsx
  src/screens/GoodFeed/GoodFeed.jsx
  src/screens/Home.jsx
  src/screens/Login/SignUp.js
  src/screens/MyPage/MyPage.jsx
  src/screens/MyPage/ProfileEdit.jsx
Labels: enhancement, API

#28 Placelist 구현
  app.json
  assets/images/news/comment_line.png
  assets/images/news/comment_logo.png
  assets/images/news/send_comment.png
  assets/images/uploadImage/default_goodNews_image.png
  assets/images/uploadImage/delete_button.png
  assets/images/uploadImage/upload_goodnews_image.png
  package-lock.json
  package.json
  src/components/News/CommentComponent.jsx
  src/components/News/GoodNewsComponent.jsx
  src/components/News/LikeComponent.jsx
  src/components/index.js
  src/navigations/GoodNews/GoodNewsStack.jsx
  src/screens/GoodNews/GoodNews.js
  src/screens/GoodNews/GoodNewsDetail.js
  src/screens/GoodNews/GoodNewsList.jsx
  src/screens/GoodNews/MakePlaceButton.jsx
  src/screens/GoodNews/PlaceList.jsx
  src/screens/GoodNews/SeeCommentDetail.js
  src/screens/GoodNews/WriteGoodNews.js
  src/screens/index.js
Labels: enhancement, API

#29 Feat: 마이페이지 API 연결
  src/components/Graph/Graph.jsx
  src/components/My/MyCommentedNews.jsx
  src/components/My/MyNews.jsx
  src/components/My/NewsList.jsx
  src/components/My/Scrap.jsx
  src/components/News/GoodNewsComponent.jsx
  src/components/News/LikeComponent.jsx
  src/hooks/index.js
  src/hooks/useNotificationSetup.js
  src/hooks/useTimeDifference.js
  src/screens/GoodNews/GoodNewsDetail.js
  src/screens/GoodNews/SeeCommentDetail.js
  src/screens/MyPage/MyPage.jsx
Labels: enhancement, API

#30 Place list axios
  assets/images/search/back_button.png
  assets/images/search/icon_gray.png
  src/components/News/DeleteModal.jsx
  src/navigations/GoodFeed/GoodFeedStack.jsx
  src/navigations/GoodNews/GoodNewsStack.jsx
  src/navigations/Home/HomeStack.jsx
  src/navigations/MainTab.jsx
  src/navigations/MyPage/MyPageStack.jsx
  src/screens/GoodNews/GoodNews.js
  src/screens/GoodNews/GoodNewsDetail.js
  src/screens/GoodNews/GoodNewsList.jsx
  src/screens/GoodNews/MakePlace.js
  src/screens/GoodNews/PlaceList.jsx
  src/screens/GoodNews/SeeCommentDetail.js
  src/screens/Search/Search.js
  src/screens/index.js
Labels: enhancement, API

#31 Feat: 알림 기능 일부 연동 및 세부 기능 수정
  App.js
  assets/splash-icon.png
  package-lock.json
  package.json
  src/components/Graph/Graph.jsx
  src/components/My/MyCommentedNews.jsx
  src/components/My/MyNews.jsx
  src/components/My/NewsList.jsx
  src/contexts/NotificationContext.jsx
  src/contexts/index.js
  src/hooks/index.js
  src/hooks/useNotificationSetup.js
  src/hooks/useSendNotification.js
  src/navigations/GoodFeed/GoodFeedStack.jsx
  src/navigations/GoodNews/GoodNewsStack.jsx
  src/navigations/Home/HomeStack.jsx
  src/navigations/MainTab.jsx
  src/navigations/MyPage/MyPageStack.jsx
  src/screens/GoodFeed/GoodFeed.jsx
  src/screens/Login/Login.js
  src/screens/Notification/Notification.jsx
Labels: enhancement, API

#33 Feat: 희소식 API 연결 수정
  src/components/News/CommentComponent.jsx
  src/screens/GoodNews/GoodNews.js
  src/screens/GoodNews/GoodNewsDetail.js
  src/screens/GoodNews/GoodNewsList.jsx
  src/screens/GoodNews/MakePlace.js
  src/screens/GoodNews/PlaceList.jsx
  src/screens/Search/Search.js
Labels: enhancement, API

#34 Feat: 희소식 null 값 해결
  src/components/My/MyCommentedNews.jsx
  src/components/My/MyNews.jsx
  src/screens/GoodNews/GoodNews.js
  src/screens/GoodNews/GoodNewsDetail.js
  src/screens/GoodNews/PlaceList.jsx
  src/screens/GoodNews/WriteGoodNews.js
Labels: bug, enhancement, API
